#!/sbin/openrc-run

name=misskey
description="Misskey daemon"

command="/usr/bin/npm"
command_args="start"
command_user="misskey"
logdir="/var/log/${name}"
output_log="${logdir}/${name}.log"
error_log="${logdir}/error.log"

supervisor="supervise-daemon"
supervise_daemon_args=" -d /opt/misskey/misskey -e NODE_ENV=\"production\""

pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need net
	use logger
}
