kind: pipeline
type: docker
name: check

volumes:
- name: guru
  temp: {}

steps:
- name: Clone ::guru
  image: alpine/git
  volumes:
  - name: guru
    path: /drone/guru
  commands:
  - git clone https://github.com/gentoo-mirror/guru.git /drone/guru

- name: repoman
  image: tastytea/repoman
  pull: always
  volumes:
  - name: guru
    path: /drone/guru
  commands:
  - mkdir /etc/portage/repos.conf
  - echo -e '[guru]\nlocation = /drone/guru' > /etc/portage/repos.conf/guru.conf
  - repoman full --include-dev --xmlparse

# - name: pkgcheck
#   image: tastytea/pkgcheck
#   pull: always
#   commands:
#   - for catpkg in $(ls -d *-*/*); do pkgcheck scan --net $${catpkg}; done

- name: notify
  image: drillster/drone-email
  pull: always
  when:
    status: [ changed, failure ]
  settings:
    host: mail.tzend.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
