kind: pipeline
type: docker
name: check all packages

volumes:
- name: guru
  temp: {}

steps:
- name: clone ::guru
  image: docker:git
  volumes:
  - name: guru
    path: /drone/guru
  commands:
  - git clone https://github.com/gentoo-mirror/guru.git /drone/guru

- name: pkgcheck
  image: tastytea/pkgcheck
  pull: always
  volumes:
  - name: guru
    path: /drone/guru
  commands:
  - echo -e '[guru]\nlocation = /drone/guru' > /etc/portage/repos.conf/guru.conf
  - pkgcheck --verbose scan --net --checks='-ImlateCheck,-RedundantVersionCheck'

- name: notify
  image: drillster/drone-email
  pull: always
  when:
    status: [ changed, failure ]
  settings:
    host: mail.tzend.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
