kind: pipeline
name: check

steps:
- name: repoman
  image: chaoslab/repoman
  pull: always
  commands:
  - repoman full --include-dev --xmlparse

- name: notify
  image: drillster/drone-email
  pull: always
  when:
    status: [ changed, failure ]
  settings:
    host: cryptoparty-celle.de
    from: drone@tzend.de
    username:
      from-secret: email_username
    password:
      from_secret: email_password
