kind: pipeline
name: check

steps:
- name: repoman
  image: tastytea/repoman
  pull: always
  commands:
  - repoman full --include-dev --xmlparse

- name: pkgcheck
  image: tastytea/repoman
  pull: always
  commands:
  - pkgcheck scan --net

- name: notify
  image: drillster/drone-email
  pull: always
  when:
    status: [ changed, failure ]
  settings:
    host: mail.tzend.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
