kind: pipeline
type: docker
name: check

steps:
- name: repoman
  image: tastytea/repoman
  pull: always
  commands:
  - mkdir /etc/portage/repos.conf
  - echo -e '[guru]\nlocation = /var/db/repos/guru\nsync-type = git\nsync-uri = https://github.com/gentoo-mirror/guru.git' > /etc/portage/repos.conf/guru.conf
  - emaint sync -r guru
  - repoman full --include-dev --xmlparse

# - name: pkgcheck
#   image: tastytea/pkgcheck
#   pull: always
#   commands:
#   - for catpkg in $(ls -d *-*/*); do pkgcheck scan --net $${catpkg}; done

- name: notify
  image: drillster/drone-email
  pull: always
  when:
    status: [ changed, failure ]
  settings:
    host: mail.tzend.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
