#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="up-common-proxies"
description="Rewrite Proxy for some UnifiedPush providers"
command="/usr/bin/up-rewrite"
pidfile="/run/${name}.pid"
logdir="/var/log/${name}"
command_background="yes"
command_user="gotify:gotify"
directory="/etc/${name}"
error_log="${logdir}/${name}.log"
command_args="-c /etc/${name}/config.toml"

depend() {
	need net
	use dns
	after logger
}
