#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="gotify-server-bin"
description="gotify server (bin)"
command="/usr/bin/${name}"
pidfile="/run/${name}.pid"
logdir="/var/log/${name}"
start_stop_daemon_args="--background --make-pidfile --pidfile ${pidfile} --user gotify:gotify --chdir /var/lib/gotify --stdout ${logdir}/${name}.log --stderr ${logdir}/error.log"

depend() {
	need net
	use dns
	after logger
}
